// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/__sitemap__/ingredients': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/__sitemap__/ingredients').default>>>>
    }
    '/api/__sitemap__/menus': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/__sitemap__/menus').default>>>>
    }
    '/api/__sitemap__/recipes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/__sitemap__/recipes').default>>>>
    }
    '/api/__sitemap__/reference': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/__sitemap__/reference').default>>>>
    }
    '/api/__sitemap__/urls': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/__sitemap__/urls').default>>>>
    }
    '/api/_content/iz-ostatkov': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/_content/iz-ostatkov.get').default>>>>
    }
    '/api/_content/iz': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/_content/iz.get').default>>>>
    }
    '/api/_content/menyu': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/_content/menyu.get').default>>>>
    }
    '/api/_content/srok-khraneniya': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/_content/srok-khraneniya.get').default>>>>
    }
    '/api/_content/zameny': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/_content/zameny.get').default>>>>
    }
    '/api/og/**:slug.png': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/og/[...slug].png').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap.xml').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.5.6_@types+node@22.7.4_db0@0.3.4_ioredis@5.10.1_lightning_4d6c68a1855b9ba02a2e67c7168efc5c/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}